name: Build & Release

on:
  workflow_dispatch:
  push:
    paths:
      - "version/version.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install pandas openpyxl customtkinter pyinstaller tkinterdnd2 requests
      
      # ===== inject version into app =====
      - name: Inject version into app
        run: python scripts/inject_version.py

      # ===== generate version info for exe =====
      - name: Generate version info for exe
        run: python scripts/generate_version.py

      # ===== build exe =====
      - name: Build exe
        run: |
            pyinstaller --onefile --noconsole --clean `
            --icon="./assets/icon.ico" `
            --version-file "./version.txt" `
            main.py


      # ===== rename exe =====
      - run: mv dist/main.exe dist/CompanyCleaner.exe

      # ===== read version =====
      - name: Read version
        run: python scripts/read_version.py

      # ===== create release FIRST =====
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: CompanyCleaner v${{ env.VERSION }}
          files: dist/CompanyCleaner.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ===== generate metadata =====
      - name: Generate SHA256 and size
        run: python generate_metadata.py

      # ===== update URL AFTER release =====
      - name: Update URL in version.json
        run: python scripts/update_url_after_release.py

      # ===== commit version.json =====
      - name: Commit version.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version/version.json
          git commit -m "update metadata [skip ci]" || echo "No changes"
          git push